### PR TITLE
YAML attribute provider

### PR DESCRIPTION
**Pull request by joshporter**
I want to layout the attributes of the magento fixtures in YAML files. Customer and SImple products seems fine, however Address and Order will have dependencies and are built up in a more complex way.

How should we manage these dependencies?

Would an Order yaml file have everything explicitly defined? Or will there be a yaml file for customer, address, product and order, and have a flag in the order file to pull in these dependencies? 

``` yaml
sales/order:
   customer: @customer
   ...
```

Would love input on where this should be going :+1:

### CODE REVIEW

**Comment by jamescowie** [comment]
Great work again Josh. Its really taking shape. 

I like the idea of relationships between the fixtures, So You would not re define all the customer attributes again in an order fixture you would just "link" however this is the more complicated means to adding data.

From working on this library what method do you feel makes sense to someone using these fixtures ?

**Comment by joshporter** [comment]
Thanks for the feedback, James.

Relationships do seem to be tricky. I was thinking of a flag in the the attribute (like above):

``` yaml
customer/customer:
    firstname: test
    lastname: test
    email: customer@example.com
    password: 123123pass
    website_id: 1
    store: 1
    status: 1
    address: @customer/address
```

A customer needs to be defined, before an address can be assigned to said customer. However, I would need to pass the customer attributes through to the address. So the Address.yml file could look like:

``` yaml
customer/address:
  customer: @customer->id
  firstname: @customer->firstname
  lastname: @customer->lastname
  company: Session Digital
  street: Brown Street
  street1: Brown Street
  city: Manchester
  postcode:  M2 2JG
  region: Lancashire
  country: United Kingdom
  country_id: GB
  telephone: 1234567890
  is_default_billing: 1
  is_default_shipping: 1
  save_in_address_book: 1
```

Passing these dependencies around, getting the order right, and keeping track of the fixtures. Complexity is starting to grow quickly!

**Comment by joshporter** [comment]
Just to give an update, I am making dependencies like this:

``` yaml
customer/address (customer/customer):
  customer: @customer->id
  firstname: @customer->firstname
  lastname: @customer->lastname
  company: Session Digital
  street: Brown Street
  street1: Brown Street
  city: Manchester
  postcode:  M2 2JG
  region: Lancashire
  country: United Kingdom
  country_id: GB
  telephone: 1234567890
  is_default_billing: 1
  is_default_shipping: 1
  save_in_address_book: 1
```

This will take from a standard set of 'template' fixtures to begin with.

**Comment by joshporter** [comment]
I have implemented dependencies in a basic manner. For a customer with an address, the Address yaml file will look like this:

``` yaml
customer/address (customer/customer):
  company: Session Digital
  street: Brown Street
  street1: Brown Street
  city: Manchester
  postcode:  M2 2JG
  region: Lancashire
  country: United Kingdom
  country_id: GB
  telephone: 1234567890
  is_default_billing: 1
  is_default_shipping: 1
  save_in_address_book: 1
```

This will create the Customer fixture (dependency) using the template in `src/MageTest/Manager/Fixtures/Customer.yml`

Using the Builder pattern previously, the create method will return the Magento customer model, and then this is passed to the AddressBuilder, with will get the attributes from the Address.yml supplied in the test, and build the fixture this way. 

Thoughts on the direction of this would be awesome :+1:

**Comment by jamescowie** [comment]
Looks great @joshporter Im really happy with how the relationships are managed via the fixtures.yml Looking at some of the more complex examples or order where you can add (product customer ) it works very intuitively. 

Ready to merge :+1:

**Pull request merged**
